import js from "@eslint/js";

export default [
  js.configs.recommended,
  {
    ignores: ["eslint.config.js"],
  },
  {
    files: ["adn-auto-skip-with-settings.user.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        // Browser
        document: "readonly",
        window: "readonly",
        console: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        navigator: "readonly",
        location: "readonly",
        localStorage: "readonly",
        fetch: "readonly",
        Request: "readonly",
        Headers: "readonly",
        AbortController: "readonly",
        AbortSignal: "readonly",
        URL: "readonly",
        Blob: "readonly",
        FileReader: "readonly",
        requestAnimationFrame: "readonly",
        cancelAnimationFrame: "readonly",
        getComputedStyle: "readonly",
        confirm: "readonly",
        // DOM
        Node: "readonly",
        Element: "readonly",
        HTMLElement: "readonly",
        HTMLVideoElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLStyleElement: "readonly",
        HTMLTextAreaElement: "readonly",
        MutationObserver: "readonly",
        IntersectionObserver: "readonly",
        KeyboardEvent: "readonly",
        MouseEvent: "readonly",
        CustomEvent: "readonly",
        Event: "readonly",
        // Tampermonkey API
        GM_info: "readonly",
        GM_xmlhttpRequest: "readonly",
        GM_addStyle: "readonly",
        GM_getValue: "readonly",
        GM_setValue: "readonly",
        GM_deleteValue: "readonly",
        GM_listValues: "readonly",
        GM_getResourceText: "readonly",
        GM_notification: "readonly",
        GM_openInTab: "readonly",
        GM_registerMenuCommand: "readonly",
        unsafeWindow: "readonly",
      },
    },
    rules: {
      "no-unused-vars": ["warn", { argsIgnorePattern: "^_" }],
      "no-console": "off",
      "no-var": "warn",
      "prefer-const": "warn",
      "eqeqeq": "warn",
      "no-alert": "warn",
      "no-eval": "warn",
      "no-undef": "warn",
      "no-empty": "warn",
    },
  },
  {
    files: ["create-docs.js"],
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "script",
      globals: {
        require: "readonly",
        module: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        process: "readonly",
        console: "readonly",
      },
    },
    rules: {
      "no-undef": "warn",
      "no-console": "off",
    },
  },
];